---
abstract: "Mojolicious â\x99¥ Mysql"
author:
  - 'Kostya Ten <kostya@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7, CPAN::Meta::Converter version 2.142690'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-Mysql
no_index:
  directory:
    - t
    - inc
    - t
requires:
  DBD::mysql: '4.028'
  DBI: '1.631'
  Mojolicious: '5.57'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/helptasker/MojoX-Mysql/issues
  license: http://opensource.org/licenses/Apache-2.0
  repository: https://github.com/helptasker/MojoX-Mysql
version: '0.03'
